stages:
  - prepare
  - package

app:prepare:
  image: alpine/git:v2.26.2
  stage: prepare
  tags:
    - kubernetes
    - cluster
  script:
    - echo "VERSION=$(git describe --tags | sed s!touhou\.fm/release/!!g)" > variables.env
  artifacts:
    reports:
      dotenv:
        - variables.env
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "touhou.fm/development" || $CI_COMMIT_BRANCH == "touhou.fm/development" || $CI_COMMIT_TAG =~ /^touhou\.fm\/release\//'
      when: on_success

app:package:
  stage: package
  image: quay.io/buildah/stable:v1.16.0
  needs:
    - job: app:prepare
      artifacts: true
  tags:
    - kubernetes
    - cluster
  before_script:
    - buildah login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - buildah bud -t "$CI_REGISTRY_IMAGE:$VERSION"
    - buildah push "$CI_REGISTRY_IMAGE:$VERSION" "docker://$CI_REGISTRY_IMAGE:$VERSION"
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "touhou.fm/development" || $CI_COMMIT_BRANCH == "touhou.fm/development" || $CI_COMMIT_TAG =~ /^touhou\.fm\/release\//'
      when: on_success

